const markerActionType = {
    GET_MARKERS_REQUESTED: 'GET_MARKERS_REQUESTED',
    GET_MARKERS_SUCCEEDED: 'GET_MARKERS_SUCCEEDED',
    ADD_MARKERS: "ADD_MARKER",
    EDIT_MARKERS: "EDIT_MARKER",
    DELETE_MARKERS: "EDIT_MARKER"
}

export default markerActionType;